### ISSUE TITLE
easy deployer VM

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1504]
```yaml
- nodegroup:
    - name: 'group_a'
      #amount of nodes to be found
      nrnodes: 5
      #cores = logical core
      nrcores_min: 10
      #gb of memory
      mem_min: 32
      ssd_min: 2000
      hdd_min: 30000
      # full machine capacity available, can it be made dedicated
      dedicated: true
      pubip4: true
      pubip6: true
      # comma separate list of region's
      # list see: https://apps.who.int/gho/data/node.searo-metadata.UNREGION?lang=en
      region: "UN_Africa,UN_Eastern_Asia"
      certified: true
      #min nr of nodes in farm
      min_nodes_farm: 5
      #nr of nodes in same farm which apply the rules above
      min_nodes_apply_rules: 3
      #bandwidth which can be achieved, do we know this?
      min_bw: 100
- sshkey:
    - name: 'despiegk'
      pubkey: ''
- vms:
    - name: 'mymachine_${nr}'
      nrvm: 4
      nodegroup: 'group_a'
      #logical cores of machine
      nrcpu: 10
      #mb of memory
      mem: 2000
      #ssd capacity in GB
      ssd: 
        -   capacity: 200
            mount: '/mydata'
      # means all HD's are given raw to VM
      hdd_attached: true
      pubip4: true
      pubip6: true
      flist: ...
      rootsize: 200
      sshkey: 'despiegk'
    - name: 'mydb'
      nodegroup: 'group_a'
      # all capacity means we create vm having access to all SSD's, to all mem, to all cores, to all HDD's, SSD all means we create dirs with no limits, each on each SSD and give as /data/1... for each ssd
      all_capacity:true
      pubip4: true
      pubip6: true
      flist: ...
      sshkey: 'despiegk'
      rootsize: 100
      


```
