### ISSUE TITLE
kubernetes usable for production

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#913]
### please test & describe how to do the following on production net

1. deploy kubernetes on prod net, 
2. deploy a node (K3s Agent I guess) on ubuntu 20.20 on a Digital Ocean machine as network node (so traffic can go in / out)
3. use wireguard on the network node, deploy a container on that node and show how the containers can talk between backend (tfgrid) and network side
4. deploy konghq on the kubernetes kluster on the network node and show how to connect to e.g. a webserver docker which was launched on the kubernetes in the tfgrid
5. show how container with flists deployed on tfgrid can talk to same network of containers in the kubernetes (inside the same wireguard network) e.g. deploy taiga using flist, and use the konghq as frontend

### purpose

- come up with a way how anyone can do production today using kubernetes & network nodes on other cloud where there is IP addr & traffic

**Comment by AhmedHanafy725** [comment]
1- Create a network from admin dashoard.
2- Deploy a Kubernetes cluster in this network.
3- Deploy a droplet on DigitalOcean (ubuntu 20.04).
4- The following steps need to be done in the DO machine.
- Install requirements.
```bash
# Install docker.
apt update
apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
apt update
apt-cache policy docker-ce
apt install -y docker-ce

# Install wireguard .
apt install -y wireguard

# Get the same version of k3s binary as the one used in our kubernetes cluster.
wget https://github.com/rancher/k3s/releases/download/v1.0.0/k3s
chmod +x k3s
```
- Configure wireguard.
  - Get the wireguard config from the network in step 1, and put it in a file lets call it `wg.conf` to be used later in configuration.
```bash
wg-quick up ./wg.conf
```
- Configure k3s agent.
  - The cluster TOKEN which can be found in the master node in this path `/var/lib/rancher/k3s/server/node-token`
  - IP:PORT of the master node (wireguard).
  - wireguard interface (the one we called `wg`)
```bash
./k3s agent --server https://IP:PORT --token TOKEN --docker --flannel-iface wg
```
5- In the cluster master check that the DO machine is connected and its status is `Ready`
```bash
kubectl get nodes
```
![image](https://user-images.githubusercontent.com/41957921/96457970-af0c3b80-1220-11eb-9838-e26fa96a77ff.png)

6- Now everything are connected and ready to use.

### Example for connecting a container on the DO machine to a container on kubernetes cluster on (tfgrid)
These steps should be done on the cluster master.
1- Start a simple python http server on cluster worker on tfgrid.
- The pod the contain the container `python_server_pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: appname1
  labels:
    app: appname1
spec:
  nodeName: "k3os-16770" #PLEASE change this to the worker name on tfgrid.
  containers:
  - name: testapp
    image: xmonader/ubudebug:latest
    command: ["/bin/bash", "-ce", "python3 -m http.server 8000"]
    ports:
      - containerPort: 8000
```
- The service to expose the python server `python_server_service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: appname1
  labels:
    name: appname1
spec:
  ports:
  - name: python
    port: 8000
  selector:
    app: appname1
```

2- Start a reverse proxy using nginx to this python http server on DO machine.
- The pod the contain the container `nginx_server_pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: appname2
  labels:
    app: appname2
spec:
  nodeName: "ubuntu-s-2vcpu-4gb-nyc1-01"  # PLEASE change this to DO machine name.
  containers:
  - name: nginx
    image: ahmedhanafy725/nginx-proxy
    command: ["/bin/bash", "-ce", "sed -i 's/SERVER_IP/appname1:8000/g' /etc/nginx/sites-available/default && service nginx start && tail -f /dev/null"]
    ports:
      - containerPort: 80
```
- The service to expose the nginx server `nginx_server_service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: appname2
  labels:
    name: appname2
spec:
  type: NodePort
  ports:
  - name: python
    nodePort: 30080
    port: 80
  selector:
    app: appname2
```
3- Apply these configuration.
- In the directory the contain these 4 yaml files.
```bash
kubectl apply -f .
```
4- Now the python server can be reached from the public IP of the DO machine with port 30080

### Example for connecting a container on the DO machine to an Ubuntu container on (tfgrid) in the same wireguard network.
1- Deploy an Ubuntu solution from admin dashboard.
2- Connect to this container and start simple python http server on port 5000.
```bash
python3 -m http.server 5000
```
3- Start nginx reverse proxy on a container on the kubernetes cluster.
- These steps should be in the cluster master.
- The pod the contain the container `nginx_server_pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: appname3
  labels:
    app: appname3
spec:
  nodeName: "ubuntu-s-2vcpu-4gb-nyc1-01"  # Here we can remove this line to create the container any where on the cluster, or use DO machine name to be deployed on.
  containers:
  - name: nginx
    image: ahmedhanafy725/nginx-proxy
    command: ["/bin/bash", "-ce", "sed -i 's/SERVER_IP/<UBUNTU_IP>:5000/g' /etc/nginx/sites-available/default && service nginx start && tail -f /dev/null"]  # PLEASE ubuntu wireguard ip here instead of <UBUNTU_IP>
    ports:
      - containerPort: 80
``` 
- The service to expose the nginx server `nginx_server_service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: appname3
  labels:
    name: appname3
spec:
  type: NodePort
  ports:
  - name: python
    nodePort: 30050
    port: 80
  selector:
    app: appname3
```
- Apply these configuration.
- In the directory the contain these 2 yaml files.
```bash
kubectl apply -f .
```
4- Now the python server can be reached from the public IP of the DO machine with port 30050

### Important Note
There is a limitation on `nodePort` service, only ports in range (30000-32767)

**Comment by despiegk** [comment]
still not good enough, we need to know how to do this and make sure the agent is not taking port 443 & 80
so we can use it for webservers if we only have 1 IP address
I am sure we can host the kubernetes agent on the wireguard address

**Comment by AhmedHanafy725** [comment]
> still not good enough, we need to know how to do this and make sure the agent is not taking port 443 & 80
> so we can use it for webservers if we only have 1 IP address
> I am sure we can host the kubernetes agent on the wireguard address
> 
> once kubernetes cluster in production there can be NO configuration requirement any more on the DO machine, all comes from Kubernetes automation

- For ports 443 & 80, they are NOT taken by the agent, and it can be used for webservers on DO machine.
- Ports 443 & 80 is only taken on the master node which is on wireguard interface.
- The agent works on wireguard interface only, unless we need to expose something to all interfaces with `nodePort` service and it will be in ports range (30000-32767).

**Comment by xmonader** [comment]
@AhmedHanafy725  not through nodeport, but through ingress. I believe you can use ingress configured to expose to the client on 80, 443,  with a tunnel between DO and k8s on the grid

**Comment by AhmedHanafy725** [comment]
## Ingress
It should solves the problem by configuring ingress in kubernetes, we can expose the application.

### Setup
1- The same setup as before for DO machine.

### Example for connecting a container running on kubernetes (tfgrid) from DO machine
These steps should be done on the cluster master.
1- Start a simple python http server on cluster worker on tfgrid.
- The pod the contain the container `python_server_pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: appname1
  labels:
    app: appname1
spec:
  containers:
  - name: testapp
    image: xmonader/ubudebug:latest
    command: ["/bin/bash", "-ce", "python3 -m http.server 8000"]
    ports:
      - containerPort: 8000
```
- The service to expose the python server `python_server_service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: appname1
  labels:
    name: appname1
spec:
  ports:
  - name: python
    port: 8000
  selector:
    app: appname1
```
- Ingress config for this python server
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appname1
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: appname1
          servicePort: 8000
```
#### With this config, we can reach the python server from the public IP of DO machine directly.

- In case we need to reach the python server from different endpoint e.g. `IP/python-server`, we can apply this config instead.
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appname1
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /python-server
        backend:
          serviceName: appname1
          servicePort: 8000
```
